import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const cases = [
  { id:'BPP-2026-000184', title:'Penarikan dana belum diterima', customer:'A*** P***', fullCustomer:'Andi Pratama', platform:'PT Bursa Digital Nusantara', category:'Dana / Withdrawal', severity:'High', status:'Platform Investigation', sla:'18 jam tersisa', slaTone:'amber', amount:'Rp 27.500.000', owner:'Finance Ops', officer:'Rina W.', note:'Nilai transaksi material, perlu bukti settlement dan log withdrawal.' },
  { id:'BPP-2026-000181', title:'Dugaan transaksi tidak sah', customer:'R*** H***', fullCustomer:'Rahmat Hidayat', platform:'PT Aset Berjangka Sejahtera', category:'Fraud / Unauthorized Transaction', severity:'Critical', status:'Escalated to Bappebti', sla:'Overdue 6 jam', slaTone:'red', amount:'Rp 84.000.000', owner:'Security & Fraud', officer:'Dimas S.', note:'Potensi fraud dan kerugian nasabah. Perlu security review dan freeze/mitigation action.' },
  { id:'BPP-2026-000178', title:'Sengketa harga eksekusi order', customer:'M*** T***', fullCustomer:'Michelle Tan', platform:'PT Komoditi Online Indonesia', category:'Transaction Dispute', severity:'High', status:'Waiting Bappebti Review', sla:'1 hari tersisa', slaTone:'amber', amount:'Rp 12.300.000', owner:'Trading Ops', officer:'Rina W.', note:'Perlu validasi trade log, timestamp order, dan market price reference.' },
  { id:'BPP-2026-000173', title:'Akun terkunci setelah proses KYC', customer:'S*** N***', fullCustomer:'Sarah Natalia', platform:'PT Bursa Digital Nusantara', category:'Account / Access', severity:'Medium', status:'Need Customer Clarification', sla:'Paused - waiting customer', slaTone:'blue', amount:'-', owner:'Customer Ops', officer:'Fajar A.', note:'SLA dipause karena menunggu dokumen klarifikasi dari pelapor.' },
  { id:'BPP-2026-000169', title:'Dugaan informasi pemasaran menyesatkan', customer:'D*** K***', fullCustomer:'Dewi Kartika', platform:'PT Sentra Perdagangan Digital', category:'Conduct / Misleading Information', severity:'Medium', status:'Assigned to Platform', sla:'2 hari tersisa', slaTone:'green', amount:'Rp 8.000.000', owner:'Compliance', officer:'Dimas S.', note:'Perlu rekaman/arsip komunikasi sales dan materi promosi terkait.' },
  { id:'BPP-2026-000166', title:'Data pribadi diduga disalahgunakan', customer:'Y*** A***', fullCustomer:'Yusuf Ardiansyah', platform:'PT Komoditi Online Indonesia', category:'Data Privacy', severity:'High', status:'Bappebti Verification', sla:'22 jam tersisa', slaTone:'amber', amount:'-', owner:'DPO / Security', officer:'Fajar A.', note:'Perlu asesmen potensi kebocoran data dan kontak pihak ketiga.' },
];

const timeline = [
  ['Pengaduan diterima','Pelapor mengirim kronologi dan bukti pendukung.','20 Mei 08:12',true],
  ['Verifikasi awal Bappebti','Kategori Dana / Withdrawal, severity High, platform teridentifikasi.','20 Mei 09:05',true],
  ['Diteruskan ke platform','PIC platform menerima notifikasi dan SLA berjalan.','20 Mei 10:42',true],
  ['Investigasi platform','Menunggu RCA, log transaksi, bukti settlement, dan action plan.','Sisa 18 jam',false],
  ['Validasi resolusi','Bappebti dan pelapor memvalidasi tindak lanjut.','Pending',false],
];

const users = [
  ['Nadia Putri','Member Admin','PT Bursa Digital Nusantara','Active','Last login 2h ago'],
  ['Ari Santoso','Finance Ops','PT Bursa Digital Nusantara','Active','Last login today'],
  ['Linda Halim','Compliance','PT Komoditi Online Indonesia','Pending Invite','Invite sent'],
  ['Reno Saputra','Security & Fraud','PT Aset Berjangka Sejahtera','Active','Last login yesterday'],
];

const orgs = [
  ['PT Bursa Digital Nusantara','Broker / Platform','Active','3 PIC','96% SLA'],
  ['PT Komoditi Online Indonesia','Platform','Active','4 PIC','88% SLA'],
  ['PT Aset Berjangka Sejahtera','Broker','Watchlist','2 PIC','71% SLA'],
  ['PT Sentra Perdagangan Digital','Platform','Active','2 PIC','93% SLA'],
];

function Logo(){return <div className="logo"><div className="logoMark">B</div><div><b>Kementerian<br/>Perdagangan</b><small>Republik Indonesia</small></div></div>}
function Badge({children,tone='pale'}){return <span className={'badge '+tone}>{children}</span>}
function Card({children, className=''}){return <div className={'card '+className}>{children}</div>}
function Button({children,onClick,secondary=false}){return <button onClick={onClick} className={secondary?'btn secondary':'btn'}>{children}</button>}
function Mini({label,value}){return <div className="mini"><small>{label}</small><b>{value}</b></div>}
function Metric({label,value,tone='navy'}){return <Card><div className="metric"><div><small>{label}</small><strong>{value}</strong></div><span className={'metricIcon '+tone}>●</span></div></Card>}

function App(){
  const [mode,setMode]=useState('public');
  const current = useMemo(()=> mode==='bappebti'?<BappebtiPortal/>:mode==='member'?<MemberPortal/>:mode==='admin'?<AdminConsole/>:<PublicSite/>,[mode]);
  return <><div className="switcher"><div className="wrap switcherInner"><Logo/><div className="modeTabs">{[['public','Customer Site'],['bappebti','Bappebti Portal'],['member','Member Portal'],['admin','Admin Console']].map(([k,l])=><button key={k} onClick={()=>setMode(k)} className={mode===k?'active':''}>{l}</button>)}</div></div></div>{current}</>
}

function PublicSite(){const [page,setPage]=useState('landing'); if(page==='service')return <ServiceFlow setPage={setPage}/>; if(page==='track')return <Tracking setPage={setPage}/>; if(page==='suggest')return <Suggestion setPage={setPage}/>; return <PublicLanding setPage={setPage}/>}
function PublicLayout({children,setPage}){return <div><div className="publicNav"><div className="wrap navLinks"><span>Beranda</span><span>Profil</span><span>Peraturan</span><span>Pelaku Pasar</span><span>Informasi Publik</span><span>Berita</span><button onClick={()=>setPage('track')}>Cek Status</button></div></div>{children}<Footer/></div>}
function Footer(){return <footer><div className="wrap foot"><div><b>Bappebti</b><p>Layanan Pengaduan Online untuk menyampaikan pengaduan, memantau tindak lanjut, dan menerima status penanganan secara transparan.</p></div><div><b>Kontak Bantuan</b><p>021-xxxx-xxxx<br/>layanan@bappebti.go.id</p></div><div><b>Jam Layanan</b><p>Senin–Jumat<br/>09.00–16.00 WIB</p></div></div></footer>}
function PublicLanding({setPage}){return <PublicLayout setPage={setPage}><section className="hero"><div className="wrap heroGrid"><div><Badge>LAYANAN PENGADUAN ONLINE BAPPEBTI</Badge><h1>Sampaikan pengaduan Anda secara resmi, mudah, dan terpantau.</h1><p>Laporkan kendala transaksi, layanan pelaku usaha, penarikan dana, akses akun, dugaan pelanggaran, atau permasalahan lain dalam ruang lingkup pengawasan Bappebti.</p><div className="actions"><Button onClick={()=>setPage('service')}>Buat Pengaduan</Button><Button secondary onClick={()=>setPage('track')}>Cek Status Tiket</Button></div><div className="heroStats"><Mini label="Tiket resmi" value="1 tiket per pengaduan"/><Mini label="SLA" value="Tindak lanjut terpantau"/><Mini label="Audit" value="Riwayat tercatat"/></div></div><Card className="flowCard"><h3>Alur Pengaduan</h3>{['Isi data pengaduan','Unggah bukti pendukung','Verifikasi Bappebti','Tindak lanjut pelaku usaha'].map((x,i)=><div className="flow" key={x}><b>0{i+1}</b><span>{x}</span></div>)}</Card></div></section><main className="wrap grid3"><Info title="Pengaduan Formal" text="Untuk keluhan yang membutuhkan verifikasi, nomor tiket, SLA, dan hasil penanganan." action="Mulai" onClick={()=>setPage('service')}/><Info title="Kritik & Saran" text="Untuk masukan layanan atau laporan umum yang tidak membutuhkan kasus formal." action="Kirim" onClick={()=>setPage('suggest')}/><Info title="Cek Status" text="Masukkan nomor tiket dan email/no. HP untuk melihat perkembangan kasus." action="Cek" onClick={()=>setPage('track')}/></main></PublicLayout>}
function Info({title,text,action,onClick}){return <Card><h3>{title}</h3><p>{text}</p><button className="linkBtn" onClick={onClick}>{action} →</button></Card>}

function ServiceFlow({setPage}){const [step,setStep]=useState(0); const titles=['Pilih jenis layanan','Identitas pelapor','Detail pengaduan','Bukti pendukung','Tinjau & kirim','Pengaduan berhasil dikirim']; return <PublicLayout setPage={setPage}><main className="wrap page"><button className="back" onClick={()=>setPage('landing')}>← Kembali ke beranda</button><h1>{titles[step]}</h1><Stepper step={step}/>{step===0&&<div className="grid3"><ServiceCard title="Pengaduan Resmi" text="Nomor tiket, verifikasi, SLA, dan tindak lanjut platform." onClick={()=>setStep(1)}/><ServiceCard title="Kritik & Saran" text="Masukan umum tanpa penanganan kasus formal." onClick={()=>setPage('suggest')}/><ServiceCard title="Panduan Memilih" text="Contoh kasus dan kanal yang tepat." onClick={()=>setPage('landing')}/></div>}{step===1&&<FormPage next={()=>setStep(2)} back={()=>setStep(0)} fields={['Nama lengkap','Nomor identitas','Email aktif','Nomor HP / WhatsApp','Provinsi domisili','Kota/Kabupaten']}/>} {step===2&&<FormPage next={()=>setStep(3)} back={()=>setStep(1)} fields={['Nama pelaku usaha / platform','User ID / Nomor akun','Kategori pengaduan','Tingkat urgensi','Tanggal kejadian','Nominal terkait','Nomor transaksi / referensi','Kronologi pengaduan']}/>} {step===3&&<UploadPage next={()=>setStep(4)} back={()=>setStep(2)}/>} {step===4&&<ReviewPage next={()=>setStep(5)} back={()=>setStep(3)}/>} {step===5&&<ConfirmPage setPage={setPage}/>}</main></PublicLayout>}
function Stepper({step}){return <div className="stepper">{['Jenis','Identitas','Detail','Bukti','Tinjau','Status'].map((x,i)=><div className={i===step?'on':i<step?'done':''} key={x}><b>{i<step?'✓':i+1}</b><span>{x}</span></div>)}</div>}
function ServiceCard({title,text,onClick}){return <Card className="selectCard"><h3>{title}</h3><p>{text}</p><Button onClick={onClick}>Pilih layanan</Button></Card>}
function FormPage({fields,next,back}){return <div className="formGrid"><Card className="formMain"><div className="inputs">{fields.map((f,i)=><label key={f} className={i>5?'wide':''}><span>{f}</span><div className={f.includes('Kronologi')?'input textarea':'input'}>{f.includes('Kronologi')?'Tuliskan kronologi dengan jelas...':'Masukkan '+f.toLowerCase()}</div></label>)}</div><Nav back={back} next={next}/></Card><SideHelp/></div>}
function SideHelp(){return <Card className="side"><h3>Catatan penting</h3><p>Gunakan data yang valid. Jangan memasukkan password, PIN, atau informasi rahasia lain.</p><ul><li>Nomor transaksi membantu verifikasi.</li><li>Bukti pendukung mempercepat proses.</li><li>Setiap status akan tercatat.</li></ul></Card>}
function UploadPage({next,back}){return <div className="formGrid"><Card className="formMain"><div className="upload">⬆<h2>Tarik file ke sini atau pilih file</h2><p>PDF, JPG, PNG. Maksimum 10MB per file.</p><Button secondary>Pilih file</Button></div><FileRow name="bukti-withdrawal.png"/><FileRow name="chat-customer-service.pdf"/><Nav back={back} next={next}/></Card><SideHelp/></div>}
function FileRow({name}){return <div className="fileRow"><span>📄 {name}</span><Badge tone="green">Berhasil diunggah</Badge></div>}
function ReviewPage({next,back}){return <Card className="formMain"><h3>Review Pengaduan</h3><ReviewRows rows={[['Nama','Andi Pratama'],['Platform','PT Bursa Digital Nusantara'],['Kategori','Dana / Withdrawal'],['Nominal','Rp 27.500.000'],['Kronologi','Dana penarikan belum diterima setelah 3 hari kerja.']]}/><div className="notice">Dengan mengirimkan pengaduan ini, pelapor menyatakan informasi yang diberikan benar.</div><Nav back={back} next={next} nextLabel="Kirim Pengaduan"/></Card>}
function ReviewRows({rows}){return <div className="reviewRows">{rows.map(([a,b])=><div key={a}><b>{a}</b><span>{b}</span></div>)}</div>}
function ConfirmPage({setPage}){return <Card className="confirm"><div className="success">✓</div><h2>Pengaduan Anda telah diterima.</h2><p>Nomor tiket dan ringkasan pengaduan telah dikirim ke email/nomor HP.</p><div className="ticket">BPP-2026-000184</div><Button onClick={()=>setPage('track')}>Lihat Status</Button></Card>}
function Nav({back,next,nextLabel='Lanjutkan'}){return <div className="navBtns"><Button secondary onClick={back}>Kembali</Button><Button onClick={next}>{nextLabel}</Button></div>}
function Tracking({setPage}){return <PublicLayout setPage={setPage}><main className="wrap page"><h1>Cek status pengaduan</h1><div className="trackGrid"><Card><label><span>Nomor tiket</span><div className="input">BPP-2026-000184</div></label><label><span>Email / No. HP</span><div className="input">andi@email.com</div></label><Button>Cek Status</Button></Card><Card><div className="caseHead"><div><small>BPP-2026-000184</small><h2>Penarikan dana belum diterima</h2><p>Platform: PT Bursa Digital Nusantara</p></div><Badge tone="amber">Dalam Proses</Badge></div><Timeline/></Card></div></main></PublicLayout>}
function Suggestion({setPage}){return <PublicLayout setPage={setPage}><main className="wrap page"><h1>Kritik & Saran</h1><Card className="formMain"><div className="inputs"><label><span>Nama</span><div className="input">Nama Anda</div></label><label><span>Email / No. HP</span><div className="input">Kontak</div></label><label className="wide"><span>Isi kritik / saran</span><div className="input textarea">Tuliskan masukan Anda...</div></label></div><Button onClick={()=>setPage('landing')}>Kirim Masukan</Button></Card></main></PublicLayout>}
function Timeline(){return <div className="timeline">{timeline.map(([a,b,c,d],i)=><div className="time" key={a}><i className={d?'done':''}>{d?'✓':'•'}</i><div><b>{a}</b><p>{b}</p><small>{c}</small></div></div>)}</div>}

function PortalLayout({title,subtitle,role,items,active,setActive,children}){return <div className="portal"><div className="wrap portalGrid"><aside><Card><small>{role}</small><h3>Complaint System</h3>{items.map(([k,l])=><button key={k} onClick={()=>setActive(k)} className={active===k?'on':''}>{l}</button>)}</Card></aside><main><div className="portalTitle"><div><h1>{title}</h1><p>{subtitle}</p></div><button className="notif">Notifications</button></div>{children}</main></div></div>}
function CaseTable({rows=cases,onOpen,memberView=false}){return <Card className="tableCard"><div className="tableTop"><div><b>Case List</b><p>Search, filter, and prioritize by SLA and severity.</p></div><div><button>Filter</button><button>Search</button></div></div><div className="scroll"><table><thead><tr><th>Ticket</th><th>Complaint</th><th>{memberView?'Customer':'Platform'}</th><th>Severity</th><th>Status / SLA</th><th>PIC</th><th>Action</th></tr></thead><tbody>{rows.map(c=><tr key={c.id}><td><code>{c.id}</code></td><td><b>{c.title}</b><small>{c.category} • {c.amount}</small></td><td>{memberView?c.customer:c.platform}</td><td><Badge tone={c.severity==='Critical'?'red':c.severity==='High'?'amber':'blue'}>{c.severity}</Badge></td><td><b>{c.status}</b><small className={c.slaTone}>{c.sla}</small></td><td>{memberView?c.owner:c.officer}</td><td><button onClick={()=>onOpen&&onOpen(c)}>Open</button></td></tr>)}</tbody></table></div></Card>}

function BappebtiPortal(){const [active,setActive]=useState('dashboard'); const [selected,setSelected]=useState(cases[0]); const items=[['dashboard','Executive Dashboard'],['ops','Operational Queue'],['case','Case Detail'],['risk','Risk Monitoring'],['memberPerf','Member Performance'],['reports','Reports']]; const title={dashboard:'Bappebti Executive Dashboard',ops:'Operational Queue',case:'Regulator Case Detail',risk:'Risk Monitoring',memberPerf:'Member Performance',reports:'Reports & Export'}[active]; return <PortalLayout title={title} subtitle="Regulator workbench for verification, assignment, SLA, escalation, and oversight." role="Bappebti Portal" items={items} active={active} setActive={setActive}>{active==='dashboard'&&<ExecutiveDashboard setActive={setActive}/>} {active==='ops'&&<CaseTable onOpen={(c)=>{setSelected(c);setActive('case')}}/>} {active==='case'&&<CaseDetail c={selected} regulator/>} {active==='risk'&&<RiskDashboard/>} {active==='memberPerf'&&<MemberPerformance/>} {active==='reports'&&<Reports/>}</PortalLayout>}
function ExecutiveDashboard({setActive}){return <><div className="metrics"><Metric label="Open Complaints" value="184" tone="blue"/><Metric label="Near Due" value="27" tone="amber"/><Metric label="Overdue" value="9" tone="red"/><Metric label="SLA Compliance" value="92%" tone="green"/></div><div className="dashGrid"><Card><h3>Complaint Trend</h3><div className="bars">{[68,45,81,52,36,73].map((h,i)=><div key={i}><span style={{height:h+'%'}}></span><small>Cat {i+1}</small></div>)}</div></Card><Card><h3>Systemic Risk Alerts</h3><Alert title="Withdrawal complaints spike" desc="18 cases from 1 member in 7 days" tone="red"/><Alert title="Ownership disputes increased" desc="6 reassignment requests pending" tone="amber"/><Alert title="Data privacy category watch" desc="3 cases under review" tone="blue"/><Button onClick={()=>setActive('risk')}>Open Risk Monitoring</Button></Card></div><CaseTable rows={cases.slice(0,4)} onOpen={()=>setActive('case')}/></>}
function Alert({title,desc,tone}){return <div className={'alert '+tone}><b>{title}</b><p>{desc}</p></div>}
function CaseDetail({c,regulator=false,setActive}){return <div className="detailGrid"><div><Card><div className="caseHead"><div><small>{c.id}</small><h2>{c.title}</h2><p>{c.platform}</p></div><Badge tone={c.severity==='Critical'?'red':c.severity==='High'?'amber':'blue'}>{c.severity}</Badge></div><div className="miniGrid"><Mini label="Customer" value={regulator?c.fullCustomer:c.customer}/><Mini label="Category" value={c.category}/><Mini label="Amount" value={c.amount}/><Mini label="SLA" value={c.sla}/></div><div className="note"><b>Risk Note</b><p>{c.note}</p></div></Card><Card><div className="tabs"><Badge tone="navy">Complaint Summary</Badge><Badge>Evidence</Badge><Badge>Member Response</Badge><Badge>Bappebti Notes</Badge><Badge>Resolution</Badge></div><ReviewRows rows={[['Platform User ID','USR-884291'],['Transaction Ref','WD-20260517-8891'],['Incident Date','17 Mei 2026'],['Current Owner',c.owner]]}/><p>Pelapor menyatakan penarikan dana belum diterima setelah 3 hari kerja. Platform diminta memberikan RCA, log transaksi, dan bukti settlement.</p></Card><Card><h3>Audit Trail & Timeline</h3><Timeline/></Card></div><div><Card><h3>{regulator?'Regulator Actions':'Member Actions'}</h3>{(regulator?['Reassign / Add Platform','Request Clarification','Approve SLA Extension','Escalate to Enforcement','Validate Resolution']:['Submit Response','Assign Internal PIC','Escalate / Reassign Request','Propose Resolution']).map(x=><button key={x} onClick={()=>x.includes('Escalate')&&setActive&&setActive('escalation')} className="actionBtn">{x}</button>)}</Card><Card><h3>Linked Cases</h3><p><code>BPP-2026-000182</code><br/>Withdrawal delayed - same member</p><p><code>BPP-2026-000179</code><br/>Settlement confirmation missing</p></Card></div></div>}
function RiskDashboard(){return <><div className="metrics"><Metric label="Critical Cases" value="11" tone="red"/><Metric label="Mass Incident Watch" value="3" tone="amber"/><Metric label="Fraud Related" value="19" tone="red"/><Metric label="Data Privacy" value="6" tone="blue"/></div><Card><h3>Risk Pattern Detection</h3><div className="grid3"><Alert title="Repeated withdrawal delay" desc="Same member, same category, 7-day window" tone="red"/><Alert title="Multiple platform involvement" desc="4 cases require ownership decision" tone="amber"/><Alert title="High value complaint" desc="3 cases above Rp 50 million" tone="red"/></div></Card><CaseTable rows={cases.filter(c=>['Critical','High'].includes(c.severity))}/></>}
function MemberPerformance(){return <Card className="tableCard"><table><thead><tr><th>Member</th><th>Open</th><th>Overdue</th><th>Avg Resolution</th><th>SLA</th><th>Risk</th></tr></thead><tbody>{[['PT Bursa Digital Nusantara','42','3','2.8 days','96%','Medium'],['PT Komoditi Online Indonesia','28','2','3.6 days','88%','Medium'],['PT Aset Berjangka Sejahtera','19','4','5.2 days','71%','High']].map(r=><tr key={r[0]}>{r.map((x,i)=><td key={x}>{i===5?<Badge tone={x==='High'?'red':'amber'}>{x}</Badge>:x}</td>)}</tr>)}</tbody></table></Card>}
function Reports(){return <div className="grid3">{['Monthly Complaint Register','Member SLA Report','Case Dossier PDF','High Risk Case List','Audit Trail Export','Category Trend Report'].map(x=><Card key={x}><h3>{x}</h3><p>Generate and export report for monitoring and audit.</p><Button secondary>Generate</Button></Card>)}</div>}

function MemberPortal(){const [active,setActive]=useState('dashboard'); const [selected,setSelected]=useState(cases[0]); const items=[['dashboard','Member Dashboard'],['cases','My Case List'],['case','Case Detail'],['escalation','Escalation Center'],['users','Member Users'],['sla','SLA Report']]; const title={dashboard:'Member Dashboard',cases:'My Assigned Cases',case:'Member Case Detail',escalation:'Escalation Center',users:'Member User Management',sla:'Member SLA Report'}[active]; return <PortalLayout title={title} subtitle="Workspace to respond, assign internal PIC, upload evidence, and request escalation." role="Member Portal" items={items} active={active} setActive={setActive}>{active==='dashboard'&&<MemberDashboard setActive={setActive}/>} {active==='cases'&&<CaseTable rows={cases.filter(c=>c.platform.includes('Bursa')||c.platform.includes('Aset'))} memberView onOpen={(c)=>{setSelected(c);setActive('case')}}/>} {active==='case'&&<><CaseDetail c={selected} setActive={setActive}/><MemberResponse/></>} {active==='escalation'&&<Escalation/>} {active==='users'&&<UserTable/>} {active==='sla'&&<><div className="metrics"><Metric label="First Response Avg" value="7.2h" tone="green"/><Metric label="Resolution Avg" value="2.8d" tone="green"/><Metric label="Extensions Requested" value="5" tone="amber"/><Metric label="Reopened" value="2" tone="red"/></div><CaseTable rows={cases.slice(0,3)} memberView/></>}</PortalLayout>}
function MemberDashboard({setActive}){return <><div className="metrics"><Metric label="Assigned Cases" value="42" tone="blue"/><Metric label="Need Response" value="11" tone="amber"/><Metric label="Overdue" value="3" tone="red"/><Metric label="SLA Compliance" value="96%" tone="green"/></div><div className="dashGrid"><Card><h3>Member Quick Actions</h3><Button onClick={()=>setActive('cases')}>Open Case List</Button><Button secondary onClick={()=>setActive('escalation')}>Submit Escalation</Button><Button secondary onClick={()=>setActive('users')}>Manage Internal PIC</Button></Card><Card><h3>Cases by Internal Team</h3>{[['Finance Ops',75],['Security & Fraud',45],['Customer Ops',36],['Compliance',30]].map(([t,w])=><div className="progress" key={t}><p>{t}</p><span><i style={{width:w+'%'}}></i></span></div>)}</Card></div><CaseTable rows={cases.slice(0,4)} memberView onOpen={()=>setActive('case')}/></>}
function MemberResponse(){return <Card><h3>Response Submission</h3><div className="inputs"><label><span>Root Cause</span><div className="input">Settlement queue delay</div></label><label><span>Estimated Completion</span><div className="input">21 Mei 2026, 15:00 WIB</div></label><label className="wide"><span>Action Taken</span><div className="input textarea">Finance operation has rechecked settlement batch and initiated manual reconciliation.</div></label></div><div className="upload small">Upload platform evidence: settlement proof, transaction log, reconciliation</div></Card>}
function Escalation(){return <div className="formGrid"><Card className="formMain"><h3>Submit Escalation / Ownership Dispute</h3><div className="inputs"><label><span>Ticket Number</span><div className="input">BPP-2026-000184</div></label><label><span>Escalation Type</span><div className="input">Request Reassignment</div></label><label><span>Proposed Owner</span><div className="input">PT Komoditi Online Indonesia</div></label><label><span>SLA Handling</span><div className="input">Request pause / continue</div></label><label className="wide"><span>Reason & Evidence Summary</span><div className="input textarea">User ID and transaction reference do not match our platform records.</div></label></div><Button>Submit to Bappebti</Button></Card><Card className="side"><h3>Allowed Escalation Types</h3>{['Request Bappebti Clarification','Request Customer Clarification','Dispute Case Ownership','Add Related Platform','SLA Extension Request','Report Suspected Fraud'].map(x=><p key={x} className="pill">{x}</p>)}</Card></div>}

function AdminConsole(){const [active,setActive]=useState('users'); const items=[['users','User Accounts'],['roles','Roles & Permissions'],['orgs','Member Master'],['sla','SLA Configuration'],['audit','Audit Logs'],['settings','System Settings']]; const title={users:'User Account Management',roles:'Roles & Permissions',orgs:'Member / Organization Master',sla:'SLA Configuration',audit:'Audit Logs',settings:'System Settings'}[active]; return <PortalLayout title={title} subtitle="Administration console for users, roles, organizations, SLA, categories, and audit logs." role="Admin Console" items={items} active={active} setActive={setActive}>{active==='users'&&<UserTable/>}{active==='roles'&&<PermissionMatrix/>}{active==='orgs'&&<OrgMaster/>}{active==='sla'&&<SLAConfig/>}{active==='audit'&&<AuditLogs/>}{active==='settings'&&<SettingsPage/>}</PortalLayout>}
function UserTable(){return <Card className="tableCard"><div className="tableTop"><b>Users</b><Button>Add User</Button></div><table><thead><tr><th>Name</th><th>Role</th><th>Organization</th><th>Status</th><th>Activity</th></tr></thead><tbody>{users.map(r=><tr key={r[0]}>{r.map((x,i)=><td key={x}>{i===3?<Badge tone={x==='Active'?'green':'amber'}>{x}</Badge>:x}</td>)}</tr>)}</tbody></table></Card>}
function PermissionMatrix(){const cols=['Customer','Member Handler','Member Admin','Bappebti Officer','Supervisor']; const rows=['Submit complaint','View customer identity','View all member cases','Reassign case','Change severity','Approve SLA extension','Close case','View internal notes','Export report']; return <Card className="tableCard"><table><thead><tr><th>Permission</th>{cols.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map((r,idx)=><tr key={r}><td>{r}</td>{cols.map((c,i)=><td key={c}><Badge tone={(idx+i)%3===0?'green':(idx+i)%3===1?'amber':'gray'}>{(idx+i)%3===0?'Yes':(idx+i)%3===1?'Limited':'No'}</Badge></td>)}</tr>)}</tbody></table></Card>}
function OrgMaster(){return <Card className="tableCard"><table><thead><tr><th>Organization</th><th>Type</th><th>Status</th><th>PIC</th><th>SLA</th></tr></thead><tbody>{orgs.map(r=><tr key={r[0]}>{r.map((x,i)=><td key={x}>{i===2?<Badge tone={x==='Watchlist'?'red':'green'}>{x}</Badge>:x}</td>)}</tr>)}</tbody></table></Card>}
function SLAConfig(){return <div className="grid3">{[['Initial Bappebti Review','1 working day'],['Member First Response','2 working days'],['Investigation Update','Every 3 working days'],['Customer Clarification','5 working days'],['Resolution Validation','2 working days'],['Critical Escalation','Immediate / same day']].map(([a,b])=><Card key={a}><h3>{a}</h3><p>{b}</p><Button secondary>Edit Rule</Button></Card>)}</div>}
function AuditLogs(){return <Card>{[['20 Mei 10:42','Rina W.','Assigned BPP-2026-000184 to PT Bursa Digital Nusantara'],['20 Mei 11:05','System','SLA near-due notification sent'],['20 Mei 11:20','Ari Santoso','Uploaded settlement reconciliation evidence'],['20 Mei 11:35','Dimas S.','Escalated BPP-2026-000181 to supervisor']].map(r=><div className="audit" key={r[0]+r[1]}><span>{r[0]}</span><b>{r[1]}</b><p>{r[2]}</p></div>)}</Card>}
function SettingsPage(){return <div className="grid3">{['Category Setup','Notification Templates','Security & MFA','File Upload Rules','Public Site Content','API Integration'].map(x=><Card key={x}><h3>{x}</h3><p>Configure system behavior and master data.</p></Card>)}</div>}

createRoot(document.getElementById('root')).render(<App />);
